### ISSUE TITLE
Identify top 30 rule set

### ISSUE THREAD

**Issue by samvaity** [Njeriiii/CodeQualityAnalyzer#2]

**Comment by Njeriiii** [comment]
Identified 12 actionable rule sets to implement [Rule sets doc](https://microsoft-my.sharepoint.com/:w:/p/t-njmwenjwa/EYvGInC2XD9EhcKe-V0J5KUB-CNN5N4CUGSJRmKN_oozBQ?e=73G50d)

Will work on processing more rule sets from the [Code Smells doc](https://microsoft-my.sharepoint-df.com/:w:/r/personal/jogiles_microsoft_com/Documents/Code%20Smells%20for%20Maven%20Build%20Tool.docx?d=wb748357a0443471fadc2ce4271c71426&csf=1&web=1&e=mIlW44)

**Comment by Njeriiii** [comment]
Completed Doc [Rule sets doc](https://microsoft-my.sharepoint.com/:w:/p/t-njmwenjwa/EYvGInC2XD9EhcKe-V0J5KUB-CNN5N4CUGSJRmKN_oozBQ?e=73G50d)
