### ISSUE TITLE
Implement a background task  functionality for periodically send telemetry data.

### ISSUE THREAD

**Issue by samvaity** [Njeriiii/CodeQualityAnalyzer#9]
This involves 
- configuring API endpoints with AppInsights for handling data transmission and ensuring secure communication between the plugin and AppInsights.
- Implement a background task that runs periodically

### >>>> 
To implement background telemetry functionality, follow these steps:

- Configure API Endpoints: Set up endpoints to send telemetry data to Azure Application Insights.
- Handle Data Transmission: Implement a background service to handle the sending of telemetry data.
- Ensure Secure Communication: Use HTTPS and appropriate authentication methods to ensure secure communication.

**Due: 06-06-2024**

Update:

**Due: 06-14-2024**

**Comment by Njeriiii** [comment]
Initially worked on this with the Connection Strings rule:
1. Configure API Endpoints: The TelemetryClient object created in TelemetryClientProvider is configured with an instrumentation key from a JSON file, which is used to identify the application to App Insights.
2. Handle Data Transmission: Sending telemetry data in the ConnectionStringCheck class. When a 'problem' is found in the code, an event is sent to Application Insights with the trackEvent method. Then immediately send the data with the flush method. This isn’t a background service, but it does send data. I tried to work on a background service that calls the trackMemoryUsage method every 60 seconds to track the memory usage of the application.
3. Azure Application Insights SDK uses HTTPS to securely send data. I don’t need to handle this myself.

https://github.com/Njeriiii/azure-tools-for-java/pull/6
